//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSomethingDoer.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageSomethingDoer.Resources.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   ImageSomethingDoer 2021 Kukuri Studio に類似しているローカライズされた文字列を検索します。
		/// </summary>
		public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Image Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutAppCmdMenu {
            get {
                return ResourceManager.GetString("AboutAppCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTooltip {
            get {
                return ResourceManager.GetString("BackgroundColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTypeBlack {
            get {
                return ResourceManager.GetString("BackgroundColorTypeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTypeBlue {
            get {
                return ResourceManager.GetString("BackgroundColorTypeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTypeChecker {
            get {
                return ResourceManager.GetString("BackgroundColorTypeChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTypeGreen {
            get {
                return ResourceManager.GetString("BackgroundColorTypeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTypeRed {
            get {
                return ResourceManager.GetString("BackgroundColorTypeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColorTypeWhite {
            get {
                return ResourceManager.GetString("BackgroundColorTypeWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseFileCmdMenu {
            get {
                return ResourceManager.GetString("CloseFileCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseFileCmdTooltip {
            get {
                return ResourceManager.GetString("CloseFileCmdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask A channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorMaskCmdATooltip {
            get {
                return ResourceManager.GetString("ColorMaskCmdATooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask B channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorMaskCmdBTooltip {
            get {
                return ResourceManager.GetString("ColorMaskCmdBTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask G channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorMaskCmdGTooltip {
            get {
                return ResourceManager.GetString("ColorMaskCmdGTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask R channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorMaskCmdRTooltip {
            get {
                return ResourceManager.GetString("ColorMaskCmdRTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show alpha channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayAlphaCmdTooltip {
            get {
                return ResourceManager.GetString("DisplayAlphaCmdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export A channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportChannelACmdMenu {
            get {
                return ResourceManager.GetString("ExportChannelACmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export B channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportChannelBCmdMenu {
            get {
                return ResourceManager.GetString("ExportChannelBCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export G channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportChannelGCmdMenu {
            get {
                return ResourceManager.GetString("ExportChannelGCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportChannelMenu {
            get {
                return ResourceManager.GetString("ExportChannelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export R channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportChannelRCmdMenu {
            get {
                return ResourceManager.GetString("ExportChannelRCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDialogFilterAll {
            get {
                return ResourceManager.GetString("FileDialogFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PNG File (*.png)|*.png|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDialogFilterPNG {
            get {
                return ResourceManager.GetString("FileDialogFilterPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display scaling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTooltip {
            get {
                return ResourceManager.GetString("ImageScalingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 1/16 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeIX16 {
            get {
                return ResourceManager.GetString("ImageScalingTypeIX16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 1/2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeIX2 {
            get {
                return ResourceManager.GetString("ImageScalingTypeIX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 1/32 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeIX32 {
            get {
                return ResourceManager.GetString("ImageScalingTypeIX32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 1/4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeIX4 {
            get {
                return ResourceManager.GetString("ImageScalingTypeIX4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 1/8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeIX8 {
            get {
                return ResourceManager.GetString("ImageScalingTypeIX8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeX1 {
            get {
                return ResourceManager.GetString("ImageScalingTypeX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 16 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeX16 {
            get {
                return ResourceManager.GetString("ImageScalingTypeX16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeX2 {
            get {
                return ResourceManager.GetString("ImageScalingTypeX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 32 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeX32 {
            get {
                return ResourceManager.GetString("ImageScalingTypeX32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeX4 {
            get {
                return ResourceManager.GetString("ImageScalingTypeX4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x 8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageScalingTypeX8 {
            get {
                return ResourceManager.GetString("ImageScalingTypeX8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load to A channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadToChannelACmdMenu {
            get {
                return ResourceManager.GetString("LoadToChannelACmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load to B channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadToChannelBCmdMenu {
            get {
                return ResourceManager.GetString("LoadToChannelBCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load to G channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadToChannelGCmdMenu {
            get {
                return ResourceManager.GetString("LoadToChannelGCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load to channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadToChannelMenu {
            get {
                return ResourceManager.GetString("LoadToChannelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load to R channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadToChannelRCmdMenu {
            get {
                return ResourceManager.GetString("LoadToChannelRCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only 32,24,8bpp images are supported for loading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelError_ChannelLoadImageBppSupport {
            get {
                return ResourceManager.GetString("ModelError_ChannelLoadImageBppSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image to be loaded does not have A channel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelError_ImageDoesNotHaveAlpha {
            get {
                return ResourceManager.GetString("ModelError_ImageDoesNotHaveAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The vertical and horizontal sizes of the image are different. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelError_ImageWidthAndHeightUnmatch {
            get {
                return ResourceManager.GetString("ModelError_ImageWidthAndHeightUnmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The main image only supports 32,24,8bpp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelError_MainImageBppSupport {
            get {
                return ResourceManager.GetString("ModelError_MainImageBppSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelError_Unsupported {
            get {
                return ResourceManager.GetString("ModelError_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileCmdMenu {
            get {
                return ResourceManager.GetString("OpenFileCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileCmdTooltip {
            get {
                return ResourceManager.GetString("OpenFileCmdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuitAppCmdMenu {
            get {
                return ResourceManager.GetString("QuitAppCmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save file as(24Bpp)(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFile24CmdMenu {
            get {
                return ResourceManager.GetString("SaveFile24CmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save file as(32Bpp)(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFile32CmdMenu {
            get {
                return ResourceManager.GetString("SaveFile32CmdMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save file as (PNG) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileCmdTooltip {
            get {
                return ResourceManager.GetString("SaveFileCmdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
    }
}
